future: true
permalink: /:title/
url: https://canyonsysu.github.io/Dashboard/
name: canyonsysu
author: canyonsysu
qq: 435191784
email: 435191784@qq.com

duoshuo: canyonsysu
beian: 
cnzz: 
weibo: 
github: canyonsysu
about: "这里是canyonsysu的团体博客，创建于 2018 年。"

safe: true
paginate: 20
